spring:
  application:
    name: kafka-mail-service

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
            type:
              mapping: 'Message : com.example.kafkademo.dto.Message'
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring:
          json:
            type:
              mapping: Message:com.example.kafkademo.dto.Message
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic: quickstart-events